services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    env_file: ../.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APP_KEY=${SpeedTestKey}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=0 0 * * *
      - DISPLAY_TIMEZONE=${TZ}
      - PRUNE_RESULTS_OLDER_THAN=7
    volumes:
      - ./config:/config
    ports:
      - 80:80
    restart: unless-stopped