services:
  metadata-remote:
    image: ghcr.io/wow-signal-dev/metadata-remote:latest
    container_name: musicmetadata
    env_file: ../.env
    ports:
      - "8338:8338"
    volumes:
      - ${MEDIA_DIR}/media/music:/music
      # To add multiple music folders, mount them as well like this:
      # - /path/to/music1:/music/Library1
      # - /path/to/music2:/music/Library2
      # ... etc.
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped